apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 
resources:
- mysql-secret.yaml
- statefulset-pv-example.yaml
- statefulset-mysql-svc.yaml
#- statefulset-mysql.yaml
- statefulset-secret-updated-mysqldb.yaml
