kind: Kustomization
resources:
- database
- exoplanets
secretGenerator:
- name: db-secrets
  literals:
    - DB_ADMIN_PASSWORD=postgres
    - DB_NAME=database
    - DB_PASSWORD=newpassword
    - DB_USER=user
configMapGenerator:
- name: db-config
  literals:
    - DB_HOST=database
    - DB_PORT=5432
